lzc-sdk-version: 0.1
package: cloud.lazycat.app.kanboard
version: 0.0.1
name: KanBoard
description: Kanboard是一个使用看板方法的项目管理软件。快速且易于使用可视化您的工作将更高效，根据您的业务活动定制您的主板。看板具有拖放任务的能力。使用现代浏览器从任何地方访问您的任务，搜索和过滤任务，所有项目的单个任务， 子任务、附件和注释，泳线、甘特图等。
license: https://choosealicense.com/licenses/mit/
homepage: https://github.com/kanboard/kanboard
application:
  subdomain: kanboard
  routes:
    # - /=http://pc.lan:8000/
    # - /=file:///lzcapp/pkg/content/
    - /=http://web.cloud.lazycat.app.kanboard.lzcapp:80
  user_app: true
services:
  web:
    image: kanboard/kanboard:latest
    environment:
      - DATABASE_URL=mysql://kanboard:kanboard-secret@${LAZYCAT_USER_ID}.db.cloud.lazycat.app.kanboard.lzcapp/kanboard
    binds:
      - /lzcapp/pkg/content/AuthController.php:/var/www/app/app/Controller/AuthController.php
      - /lzcapp/pkg/content/login.js:/var/www/app/assets/js/components/login.js
      - /lzcapp/pkg/content/index.php:/var/www/app/app/Template/auth/index.php
      - /lzcapp/var/kanboard_data:/var/www/app/data
      - /lzcapp/var/kanboard_plugins:/var/www/app/plugins
  db:
    image: mariadb:11.0.2
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=kanboard
      - MYSQL_USER=kanboard
      - MYSQL_PASSWORD=kanboard-secret
    binds:
      - /lzcapp/var/mysql:/var/lib/mysql
