application:
  routes:
  - /=http://minecraftserver.cloud.lazycat.app.minecraftserver.lzcapp:3000
  subdomain: minecraftserver
description: '### Overview


  This app packages the Minecraft Java Edition server <upstream>1.18</upstream>


  Minecraft is a game about breaking and placing blocks. At first, people built structures
  to protect against nocturnal monsters, but as the game grew players worked together
  to create wonderful, imaginative things.


  ### User Management


  The Cloudron user management options only apply to the server dashboard. Minecraft
  clients login through the Minecraft accounts.

  '
lzc-sdk-version: '0.1'
name: Minecraft Server
package: cloud.lazycat.app.minecraftserver
services:
  minecraftserver:
    image: cloudron/net.minecraft.cloudronapp:20211202-145158-699a916f1
version: 1.6.10
