application:
  routes:
  - /=http://releasebell.cloud.lazycat.app.releasebell.lzcapp:3000
  subdomain: releasebell
description: 'This app packages Release Bell <upstream>1.7.1</upstream>


  ### Overview


  Release Bell tracks your starred GitHub repositories and will notify you on every
  new tag or release.

  Furthermore it allows to manually track GitLab project releases.


  All notifications are sent out via email.

  '
lzc-sdk-version: '0.1'
name: ReleaseBell
package: cloud.lazycat.app.releasebell
services:
  mysql:
    binds:
    - /lzcapp/var/mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=LAZYCAT
    - MYSQL_DATABASE=LAZYCAT
    - MYSQL_USER=LAZYCAT
    - MYSQL_PASSWORD=LAZYCAT
    image: registry.lazycat.cloud/mysql
  releasebell:
    environment:
    - CLOUDRON_PROXY_IP=host.lzcapp
    - CLOUDRON_LDAP_SERVER=host.lzcapp
    - CLOUDRON_LDAP_HOST=host.lzcapp
    - CLOUDRON_LDAP_PORT=389
    - CLOUDRON_LDAP_URL=ldap://host.lzcapp:389
    - CLOUDRON_LDAP_USERS_BASE_DN=ou=users,dc=heiyu,dc=space
    - CLOUDRON_LDAP_GROUPS_BASE_DN=ou=groups,dc=lazycat
    - CLOUDRON_LDAP_BIND_DN=cn=admin,dc=heiyu,dc=space
    - CLOUDRON_LDAP_BIND_PASSWORD=unsafe_password
    - CLOUDRON_API_ORIGIN=https://releasebell.${LAZYCAT_BOX_DOMAIN}
    - CLOUDRON_APP_ORIGIN=https://releasebell.${LAZYCAT_BOX_DOMAIN}
    - CLOUDRON_APP_DOMAIN=releasebell.${LAZYCAT_BOX_DOMAIN}
    - CLOUDRON_MYSQL_HOST=mysql.cloud.lazycat.app.releasebell.lzcapp
    - CLOUDRON_MYSQL_PORT=3306
    - CLOUDRON_MYSQL_DATABASE=LAZYCAT
    - CLOUDRON_MYSQL_USERNAME=LAZYCAT
    - CLOUDRON_MYSQL_PASSWORD=LAZYCAT
    - CLOUDRON_MAIL_SMTP_SERVER=mail
    - CLOUDRON_MAIL_SMTP_PORT=2525
    - CLOUDRON_MAIL_SMTPS_PORT=2465
    - CLOUDRON_MAIL_STARTTLS_PORT=2587
    - CLOUDRON_MAIL_SMTP_USERNAME=wiki.app@xxx.heiyu.space
    - CLOUDRON_MAIL_SMTP_PASSWORD=666666
    - CLOUDRON_MAIL_FROM=wiki.app@xxx.heiyu.space
    - CLOUDRON_MAIL_DOMAIN=xxx.heiyu.space
    image: cloudron/io.cloudron.releasebell:20210617-085625-2429d1105
version: 1.7.11
