lzc-sdk-version: 0.1
package: cloud.lazycat.app.rustdeskoss
version: 0.0.2
name: rustdeskoss
description: >-
  RustDesk is a full-featured open source remote control alternative for
  self-hosting and security with minimal configuration.
license: https://choosealicense.com/licenses/mit/
homepage: https://rustdesk.com
author: rustdesk term
application:
  subdomain: rustdeskoss
  routes:
    - /web=http://web.cloud.lazycat.app.rustdeskoss.lzcapp:5000
    - /key=file:///lzcapp/var/rustdeskoss.key
    - /=file:///lzcapp/pkg/content/public
  handlers:
    error_page_templates:
      '502': /lzcapp/pkg/content/public/502.html.tpl
  background_task: true

  # ingress:
  #   - protocol: tcp
  #     port: 21115
  #     service: hbbs
  #   - protocol: tcp
  #     port: 21116
  #     service: hbbs
  #   - protocol: tcp
  #     port: 21118
  #     service: hbbs
  #   - protocol: udp
  #     port: 21116
  #     service: hbbs

  #   - protocol: tcp
  #     port: 21117
  #     service: hbbr
  #   - protocol: tcp
  #     port: 21119
  #     service: hbbr


services:
  web:
    image: registry.lazycat.cloud/keyurbhole/flutter_web_desk:v1.0.0
    
  hbbs:
    image: registry.lazycat.cloud/rustdesk/rustdesk-server:1.1.11-1
    command: /lzcapp/pkg/content/randkey
    binds:
      - /lzcapp/var/data:/root
    network_mode: "host"
    depends_on:
      - hbbr

  hbbr:
    image: registry.lazycat.cloud/rustdesk/rustdesk-server:1.1.11-1
    command: hbbr
    binds:
      - /lzcapp/var/data:/root
    network_mode: "host"
