application:
  routes:
  - /=http://filebrowser.cloud.lazycat.app.filebrowser.lzcapp:80
  subdomain: filebrowser
description: 轻量级文件管理器，可用于上传、删除、预览、重命名和编辑您的文件。
lzc-sdk-version: '0.1'
name: 文件管理
package: cloud.lazycat.app.filebrowser
services:
  filebrowser:
    binds:
    - /lzcapp/var:/app/
    - /lzcapp/var:/srv
    - /lzcapp/pkg/./sudo-1.9.8_p2-r1.apk:/app/sudo-1.9.8_p2-r1.apk
    - /lzcapp/pkg/./filebrowser.json:/.filebrowser.json:ro
    - /lzcapp/pkg/./start.sh:/start.sh
    entrypoint: sh /start.sh
    environment:
    - APP_ORIGIN=${LAZYCAT_APP_ORIGIN}
    image: filebrowser/filebrowser:v2.20.1
version: 2.20.11
