description: 用于使用Git，以及其他协作、托管、开发版本控制
lzc-sdk-version: '0.1'
name: Gitea
package: cloud.lazycat.app.gitea
version: 1.24.6-patch1
application:
  routes:
  - /=http://gitea.cloud.lazycat.app.gitea.lzcapp:3000
  subdomain: gitea
  background_task: true
  public_path:
    - /
  ingress:
    - protocol: tcp     #tcp or udp
      port: 22          #需要曝露的端口号
      service: gitea
services:
  gitea:
    binds:
    - /lzcapp/pkg/content/start.sh:/start.sh
    - /lzcapp/var/data:/data
    setup_script: /usr/bin/entrypoint /start.sh
    environment:
    - INSTALL_LOCK=true
    - LFS_START_SERVER=true
    - USER_UID=${BOX_UID}
    - USER_GID=${BOX_GID}
    - DOMAIN=gitea.${LAZYCAT_BOX_DOMAIN}
    - SSH_DOMAIN=gitea.${LAZYCAT_BOX_DOMAIN}
    - LDAP_HOST=${LAZYCAT_AUTH_LDAP_HOST}
    - LDAP_PORT=${LAZYCAT_AUTH_LDAP_PORT}
    - LDAP_BASE_DN=${LAZYCAT_AUTH_LDAP_BASE_DN}
    - LDAP_BIND_DN=${LAZYCAT_AUTH_LDAP_BIND_DN}
    - LDAP_BIND_PASS=${LAZYCAT_AUTH_LDAP_BIND_PASS}
    image: registry.lazycat.cloud/u7842111934/gitea/gitea:ee1d72007c5a021f # gitea/gitea:1.24.6
