lzc-sdk-version: 0.1
package: cloud.lazycat.app.onenav
version: 0.0.2
name: OneNav
description: 一个简单轻快的书签管理系统，将浏览器书签集中式管理，做到一处部署，随处访问。
license: https://choosealicense.com/licenses/apache-2.0/
homepage: https://github.com/helloxz/onenav
application:
  subdomain: onenav
  routes:
    # - /=http://pc.lan:8000/
    # - /=file:///lzcapp/pkg/content/
    - /=http://web.cloud.lazycat.app.onenav.lzcapp:80
  user_app: true

services:
  web:
    image: registry.lazycat.cloud/appdb/onenav:202307201
    binds:
      - /lzcapp/var/data:/var/www/html/data