lzc-sdk-version: 0.1
package: cloud.lazycat.app.tinytinyrss
version: 0.0.3
name: Tiny Tiny RSS
description: Tiny Tiny RSS 是一个免费和开源的基于网络的新闻提要 (RSS/Atom) 阅读器和聚合器
license: https://choosealicense.com/licenses/mit/
homepage: https://tt-rss.org/
application:
  subdomain: ttrss
  routes:
    - /=http://$uid.web.cloud.lazycat.app.tinytinyrss.lzcapp:8280
  user_app: true
# https://tt-rss.org/wiki/InstallationNotes/
services:
  # registry.lazycat.cloud/tt-rss-feedly-theme:4.1.0
  db:
    image: postgres:16.3-bookworm
    environment:
      - POSTGRES_DB=ttrss
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrss
      - PGDATA=/lzcapp/var/pgdata
  web:
    depends_on:
      - db
    image: cthulhoo/ttrss-fpm-pgsql-static:8fe28cfc # Mon Jul 15 2024 13:14:10 GMT+0800
    environment:
      - TTRSS_DB_HOST=${LAZYCAT_USER_ID}.db.cloud.lazycat.app.tinytinyrss.lzcapp
      - TTRSS_DB_PORT=5432
      - TTRSS_DB_USER=ttrss
      - TTRSS_DB_PASS=ttrss
      - TTRSS_DB_NAME=ttrss
      - TTRSS_SINGLE_USER=true
      - TTRSS_SIMPLE_UPDATE_MODE=false
      - TTRSS_SELF_REGISTRATION=false
      - TTRSS_MAX_USERS=1
      - REFRESH_INTERVAL_MINUTES=15
      - TTRSS_SMTP_FROM_NAME=TinyTinyRSS
      - TTRSS_SMTP_ADDRESS=no-reply@example.org
      - TTRSS_SMTP_SERVER=smtp.example.org.org:25
      - TTRSS_SMTP_USER=no-reply@example.org
      - TTRSS_SMTP_PASSWORD=SmTpPassw0rd
      - TTRSS_SMTP_SECURE_METHOD=
      - TTRSS_SELF_URL_PATH=https://${LAZYCAT_APP_ORIGIN}/
  web-nginx:
    image: cthulhoo/ttrss-web-nginx:latest
    environment:
      - TTRSS_URI=https://${LAZYCAT_APP_ORIGIN}/
      - HTTP_PORT=8280
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app
