lzc-sdk-version: 0.1
package: cloud.lazycat.app.affine
version: 0.0.1
name: AFFiNE
description: There can be more than Notion and Miro. AFFiNE is a next-gen knowledge base that brings planning, sorting and creating all together. Privacy first, open-source, customizable and ready to use.
license: https://www.mozilla.org/en-US/MPL/2.0
homepage: https://github.com/toeverything/AFFiNE
author: d1y

application:
  subdomain: affine
  background_task: false
  routes:
    - /=http://affine.cloud.lazycat.app.affine.lzcapp:3010
  user_app: false
services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    depends_on:
      - redis
      - postgres
      - affine_migration
    binds:
      - /lzcapp/var/storage:/root/.affine/storage
      - /lzcapp/var/config:/root/.affine/config
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://affine:affine@postgres:5432/affine
      - AFFINE_SERVER_EXTERNAL_URL=https://affine.${LAZYCAT_BOX_DOMAIN}

  affine_migration:
    image: ghcr.io/toeverything/affine-graphql:stable
    binds:
      # custom configurations
      - /lzcapp/var/storage:/root/.affine/storage
      - /lzcapp/var/config:/root/.affine/config
    command: |
      sh -c 'node ./scripts/self-host-predeploy.js && sleep 100000'
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://affine:affine@postgres:5432/affine
    depends_on:
      - postgres
      - redis

  redis:
    image: redis

  postgres:
    image: pgvector/pgvector:pg16
    binds:
      - /lzcapp/var/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=affine
      - POSTGRES_PASSWORD=affine
      - POSTGRES_DB=affine
      - POSTGRES_INITDB_ARGS='--data-checksums'
      - POSTGRES_HOST_AUTH_METHOD=trust

