version: "3.9"
x-lazycat-metadata:
  id: photoprism
  icon: icon_photoprism.png
  title: Photoprism
  summary: 相册管理
  screenshots:
    - screenshot_photoprism.png
  categories:
    - files
services:
  photoprism:
    image: photoprism/photoprism:20211018
    environment:
    - PHOTOPRISM_ADMIN_PASSWORD=admin
    - PHOTOPRISM_UPLOAD_NSFW=true
    labels:
      ingress-2342: photoprism
