#!/bin/sh
touch /app/storage/app/cookie.txt

cp /lzcapp/pkg/content/.env /app/.env
echo CP exit $?
sed -i s/USER_ID/$LAZYCAT_USER_ID/g /app/.env
sed -i s/LAZYCAT_APP_DOMAIN/$LAZYCAT_APP_DOMAIN/g /app/.env
cat /app/.env
grep -n REDIS /app/.env

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"

echo exit $?

